spring:
  application:
    name: jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
